name: Continuous Integration
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

       - name: Setup go
         uses: actions/setup-go@v3
         with:
           go-version: '1.17'

       - run: go test -v ./... -cover